Revert "x86/fpu: Move FPU initialization into arch_cpu_finalize_init()"
This reverts commit 4ae1cbb730bd574d57d3996d4c20974972d47009.

We found this commit would cause warnings during FPU initilization
in all EC2 Nitro instances:

[    0.832860] ------------[ cut here ]------------
[    0.832860] get of unsupported state
[    0.832860] WARNING: CPU: 0 PID: 0 at arch/x86/kernel/fpu/xstate.c:879 get_xsave_addr+0x81/0x90
[    0.832860] Modules linked in:
[    0.832860] Hardware name: Amazon EC2 c5.large/, BIOS 1.0 10/16/2017
[    0.832860] RIP: 0010:get_xsave_addr+0x81/0x90
[    0.832860] Code: 5b c3 48 83 c4 08 31 c0 5b c3 80 3d 7c ea 78 01 00 75 c1 48 c7 c7 1c a6 03 82 89 4c 24 04 c6 05 68 ea 78 01 01 e8 4f 4c 05 00 <0f> 0b 48 63 4c 24 04 eb a1 31 c0 c3 0f 1f 00 0f 1f 44 00 00 41 54
[    0.832860] RSP: 0000:ffffffff82603ed0 EFLAGS: 00010282
[    0.832860] RAX: 0000000000000000 RBX: ffffffff827ebfc0 RCX: 0000000031a47119
[    0.832860] RDX: 0000000000000018 RSI: ffffffff839eb960 RDI: ffffffff839e952c
[    0.832860] RBP: ffffffff827ebe80 R08: 7520666f20746567 R09: 74726f707075736e
[    0.832860] R10: 00000000000962fc R11: 6574617473206465 R12: ffffffff82d8bb60
[    0.832860] R13: 0000000000000246 R14: 0000000000000000 R15: 0000000000000000
[    0.832860] FS:  0000000000000000(0000) GS:ffff88812ca00000(0000) knlGS:0000000000000000
[    0.832860] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    0.832860] CR2: ffff888130dff000 CR3: 000000000260a001 CR4: 00000000007200b0
[    0.832860] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[    0.832860] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[    0.832860] Call Trace:
[    0.832860]  ? __warn+0x85/0xcc
[    0.832860]  ? get_xsave_addr+0x81/0x90
[    0.832860]  ? report_bug+0xb6/0x130
[    0.832860]  ? get_xsave_addr+0x81/0x90
[    0.832860]  ? fixup_bug.part.12+0x18/0x30
[    0.832860]  ? do_error_trap+0x95/0xb0
[    0.832860]  ? do_invalid_op+0x36/0x40
[    0.832860]  ? get_xsave_addr+0x81/0x90
[    0.832860]  ? invalid_op+0x1e/0x30
[    0.832860]  ? get_xsave_addr+0x81/0x90
[    0.832860]  identify_cpu+0x422/0x510
[    0.832860]  identify_boot_cpu+0xc/0x94
[    0.832860]  arch_cpu_finalize_init+0x5/0x4a
[    0.832860]  start_kernel+0x461/0x50a
[    0.832860]  secondary_startup_64+0xa4/0xb0
[    0.832860] ---[ end trace 943bbb1c8b55b8c0 ]---

Given this commit is not a functional change, revert it for clean boot.